//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundaPaginaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaCompraXProducto
    {
        public int idListaCompra { get; set; }
        public int idProducto { get; set; }
        public int costoTotal { get; set; }
    
        public virtual ListaCompra ListaCompra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
