//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundaPaginaWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fasbdEntities7 : DbContext
    {
        public fasbdEntities7()
            : base("name=fasbdEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Historial> Historial { get; set; }
        public virtual DbSet<ListaCompra> ListaCompra { get; set; }
        public virtual DbSet<ListaCompraXProducto> ListaCompraXProducto { get; set; }
        public virtual DbSet<ListaFavoritoProducto> ListaFavoritoProducto { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProductoXTienda> ProductoXTienda { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<promocionxTiendaProducto> promocionxTiendaProducto { get; set; }
        public virtual DbSet<Tienda> Tienda { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
