//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundaPaginaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoXTienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoXTienda()
        {
            this.promocionxTiendaProducto = new HashSet<promocionxTiendaProducto>();
        }
    
        public int idProducto { get; set; }
        public int tDisponibilidad { get; set; }
        public int Tienda_idTienda { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Tienda Tienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocionxTiendaProducto> promocionxTiendaProducto { get; set; }
    }
}
