//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundaPaginaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ListaCompraXProducto = new HashSet<ListaCompraXProducto>();
            this.ListaFavoritoProducto = new HashSet<ListaFavoritoProducto>();
        }
    
        public int idProducto { get; set; }
        public string nNombre { get; set; }
        public string dImagen { get; set; }
        public string nPrecio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaCompraXProducto> ListaCompraXProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaFavoritoProducto> ListaFavoritoProducto { get; set; }
        public virtual ProductoXTienda ProductoXTienda { get; set; }
    }
}
