//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundaPaginaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocionxTiendaProducto
    {
        public int idPromocionTiendaProducto { get; set; }
        public int idPromocion { get; set; }
        public int ProductoXTienda_idProducto { get; set; }
    
        public virtual ProductoXTienda ProductoXTienda { get; set; }
        public virtual Promocion Promocion { get; set; }
    }
}
