//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundaPaginaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tienda()
        {
            this.ListaCompra = new HashSet<ListaCompra>();
            this.ProductoXTienda = new HashSet<ProductoXTienda>();
        }
    
        public int idTienda { get; set; }
        public string tRUC { get; set; }
        public string dUbicacion { get; set; }
        public string tDescripcion { get; set; }
        public string tCorreo { get; set; }
        public string tcontrasena { get; set; }
        public byte[] tLogo { get; set; }
        public Nullable<bool> Permiso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaCompra> ListaCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoXTienda> ProductoXTienda { get; set; }
    }
}
